### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by mangao05** [benitolopez/hotel-datepicker#77]
Does it have responsiveness on mobile view or in any breaking point? If it has, it seems that its not working fine on my site? Thank you

**Comment by benitolopez** [comment]
Yews it is responsive. When the screen is less than 480px it shows one month only (you need to refresh the page). 

What is the URL of your website?

**Comment by mangao05** [comment]
havendwellresort.com.ph, can you tell whats wrong in it? thank you

**Comment by benitolopez** [comment]
That's because you're using a custom padding for the table cells. You have this:

```css
.datepicker__month-day {
  -webkit-transition-duration: 0.2s;
          transition-duration: 0.2s;
  -webkit-transition-property: color, background-color, border-color;
  transition-property: color, background-color, border-color;
  -webkit-transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
          transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  color: black;
  font-weight: bold;
  padding: 19px 17px;
}
```

But the original CSS has less padding:

```css
.datepicker__month-day {
  padding: 9px 7px;
}
```

Decrease the padding or write your custom CSS to adapt your needs. I'm closing the issue because this is not a bug of the library but something related to your custom CSS.
